import type { VisaCase, ZohoDeal } from '../types/crm';

export const mockDeals: ZohoDeal[] = [
  {
    id: '1',
    Contact_Name: { name: 'Putri Ashdini Mohd Khairuddin' },
    Account_Name: { name: 'Kingston University' },
    Owner: { name: 'Teddy Low' },
    Stage: 'Admissions',
    Country: 'United Kingdom',
    Course_Title: 'MSc Occupational and Business Psychology',
    Intake_Month: 'September',
    Intake_Year: '2026',
    Student_Applicant_ID: 'KNG-2026-001',
    Student_Type: 'Claimable (CS)',
    Degree_Entry_Level: 'Master (Coursework)',
    Email: 'ashdini002@gmail.com',
    Mobile: '447933895863',
    Stage_Modified_Time: '2026-07-03T03:40:02+08:00',
    Last_Activity_Time: '2026-07-03T09:44:01+08:00',
    Remarks: 'Opts for the 2 year master program',
    To_Sub_Agent: 'SI-UK',
    Portal: 'https://example.com/portal',
    Username: 'ashdini002',
    Expected_Revenue: 2800,
  },
  {
    id: '2',
    Contact_Name: { name: 'Nur Syarah Humayra Omar Ali' },
    Account_Name: { name: 'Oxford Brookes University' },
    Owner: { name: 'Admissions Team' },
    Stage: 'Request CAS',
    Country: 'United Kingdom',
    Course_Title: 'MA Journalism',
    Intake_Month: 'September',
    Intake_Year: '2026',
    Start_Date: '2026-09-14',
    Tuition_Fee: 'GBP 18500',
    Expected_Revenue: 2405,
    Stage_Modified_Time: '2026-06-20T18:46:33+08:00',
    Student_Applicant_ID: '19282541',
    Offer_Acceptance_Deadline: '2026-03-22',
    Offer_Attachment: [{ file_Name: 'Nur Syarah Humayra - OBU Uncond Offer Letter.pdf', file_Size: '596 KB', extn: 'pdf' }],
  },
  {
    id: '3',
    Contact_Name: { name: 'Faheera Abdul Rahim' },
    Account_Name: { name: 'University of Queensland' },
    Owner: { name: 'Admissions Team' },
    Stage: 'Preparing Documents',
    Country: 'Australia',
    Course_Title: 'Bachelor of Architectural Design',
    Intake_Month: 'February',
    Intake_Year: '2027',
    Stage_Modified_Time: '2026-06-22T16:42:31+08:00',
    Course_Link: 'https://study.uq.edu.au/',
    Expected_Revenue: 3500,
  },
  {
    id: '4',
    Contact_Name: { name: 'Aaron Harris Hashim' },
    Account_Name: { name: 'University of Leeds' },
    Owner: { name: 'Teddy Low' },
    Stage: 'Pending Offer (3 weeks passed)',
    Country: 'United Kingdom',
    Course_Title: 'MSc Data Science',
    Intake_Month: 'September',
    Intake_Year: '2026',
    Stage_Modified_Time: '2026-06-05T10:00:00+08:00',
    Last_Activity_Time: '2026-06-10T10:00:00+08:00',
    Expected_Revenue: 3100,
  },
];

export const mockVisaCases: VisaCase[] = [
  { id: 'v1', student: 'Aaron Harris Hashim', country: 'United Kingdom', visaType: 'Student Visa', stage: 'New', owner: 'Visa Team', daysInStage: 1 },
  { id: 'v2', student: 'Mei Yee Yap', country: 'United Kingdom', visaType: 'Student Visa', stage: 'Ready for Checking', owner: 'Visa Team', daysInStage: 4 },
  { id: 'v3', student: 'Allissa Noemi Soon', country: 'Australia', visaType: 'Visitor Visa', stage: 'Submitted Online', owner: 'Teddy Low', daysInStage: 6 },
  { id: 'v4', student: 'Aisyah Nazreen Naslah', country: 'United Kingdom', visaType: 'Student Visa', stage: 'Submitted Biometrics', owner: 'Visa Team', daysInStage: 2 },
  { id: 'v5', student: 'Lee Ping', country: 'United Kingdom', visaType: 'Student Visa', stage: 'Visa Approved', owner: 'Visa Team', daysInStage: 0 },
];
